/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "D:\\study\\CMS\\view\\vuepress\\1.vuepress-starter\\node_modules\\_@vuepress_core@1.5.4@@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "D:\\study\\CMS\\view\\vuepress\\1.vuepress-starter\\node_modules\\_@vuepress_plugin-nprogress@1.5.4@@vuepress\\plugin-nprogress\\clientRootMixin.js"
import m2 from "D:\\study\\CMS\\view\\vuepress\\1.vuepress-starter\\node_modules\\_vuepress-plugin-smooth-scroll@0.0.3@vuepress-plugin-smooth-scroll\\lib\\clientRootMixin.js"
import m3 from "D:\\study\\CMS\\view\\vuepress\\1.vuepress-starter\\node_modules\\_@vuepress_plugin-active-header-links@1.5.4@@vuepress\\plugin-active-header-links\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3
]