/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\study\\CMS\\view\\vuepress\\1.vuepress-starter\\node_modules\\_@vuepress_core@1.5.4@@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-db339912",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db339912").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-51dd0297",
    path: "/project/declarationspaces.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51dd0297").then(next)
    },
  },
  {
    name: "v-155d1a1f",
    path: "/project/compilationContext.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-155d1a1f").then(next)
    },
  },
  {
    name: "v-2ea09a28",
    path: "/config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ea09a28").then(next)
    },
  },
  {
    name: "v-42959f49",
    path: "/project/dynamicImportExpressions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42959f49").then(next)
    },
  },
  {
    name: "v-73098e57",
    path: "/project/modules.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73098e57").then(next)
    },
  },
  {
    name: "v-622dba07",
    path: "/project/namespaces.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-622dba07").then(next)
    },
  },
  {
    name: "v-297476d7",
    path: "/typings/ambient.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-297476d7").then(next)
    },
  },
  {
    name: "v-3bdea20d",
    path: "/typings/callable.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bdea20d").then(next)
    },
  },
  {
    name: "v-b1c68552",
    path: "/typings/enums.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b1c68552").then(next)
    },
  },
  {
    name: "v-685f24fa",
    path: "/typings/discrominatedUnion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-685f24fa").then(next)
    },
  },
  {
    name: "v-ca22b292",
    path: "/typings/exceptionsHanding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ca22b292").then(next)
    },
  },
  {
    name: "v-cb193a12",
    path: "/typings/freshness.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cb193a12").then(next)
    },
  },
  {
    name: "v-076dbaf7",
    path: "/typings/generices.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-076dbaf7").then(next)
    },
  },
  {
    name: "v-72dc9137",
    path: "/typings/functions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72dc9137").then(next)
    },
  },
  {
    name: "v-7854de12",
    path: "/typings/indexSignatures.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7854de12").then(next)
    },
  },
  {
    name: "v-1e0adf89",
    path: "/typings/interfaces.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e0adf89").then(next)
    },
  },
  {
    name: "v-20d9ddf7",
    path: "/typings/lib.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20d9ddf7").then(next)
    },
  },
  {
    name: "v-d4852596",
    path: "/typings/literals.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d4852596").then(next)
    },
  },
  {
    name: "v-043429d2",
    path: "/typings/migrating.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-043429d2").then(next)
    },
  },
  {
    name: "v-66ae3d99",
    path: "/typings/mixins.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66ae3d99").then(next)
    },
  },
  {
    name: "v-b4331e92",
    path: "/typings/movingTypes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b4331e92").then(next)
    },
  },
  {
    name: "v-50981f52",
    path: "/typings/neverType.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50981f52").then(next)
    },
  },
  {
    name: "v-6d54244b",
    path: "/typings/overview.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d54244b").then(next)
    },
  },
  {
    name: "v-a276470e",
    path: "/typings/readonly.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a276470e").then(next)
    },
  },
  {
    name: "v-22bccd8d",
    path: "/typings/thisType.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22bccd8d").then(next)
    },
  },
  {
    name: "v-fda1b0d2",
    path: "/typings/typeAssertion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fda1b0d2").then(next)
    },
  },
  {
    name: "v-032b0557",
    path: "/typings/typeCompatibility.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-032b0557").then(next)
    },
  },
  {
    name: "v-22230992",
    path: "/typings/typeGuard.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22230992").then(next)
    },
  },
  {
    name: "v-7492fbb7",
    path: "/typings/typeInference.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7492fbb7").then(next)
    },
  },
  {
    name: "v-ba480312",
    path: "/typings/types.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba480312").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]