/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "我是主标题!",
  "description": "我的第一个vuepress项目",
  "base": "/ts/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/ts/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "我是本书作者",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-db339912",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "Why",
          "slug": "why"
        },
        {
          "level": 2,
          "title": "翻译内容",
          "slug": "翻译内容"
        },
        {
          "level": 2,
          "title": "How to contribute",
          "slug": "how-to-contribute"
        },
        {
          "level": 2,
          "title": "最后",
          "slug": "最后"
        }
      ]
    },
    {
      "title": "声明空间",
      "frontmatter": {},
      "regularPath": "/project/declarationspaces.html",
      "relativePath": "project/declarationspaces.md",
      "key": "v-51dd0297",
      "path": "/project/declarationspaces.html",
      "headers": [
        {
          "level": 2,
          "title": "类型声明空间",
          "slug": "类型声明空间"
        },
        {
          "level": 2,
          "title": "变量声明空间",
          "slug": "变量声明空间"
        }
      ]
    },
    {
      "title": "编译上下文",
      "frontmatter": {},
      "regularPath": "/project/compilationContext.html",
      "relativePath": "project/compilationContext.md",
      "key": "v-155d1a1f",
      "path": "/project/compilationContext.html",
      "headers": [
        {
          "level": 2,
          "title": "tsconfig.json",
          "slug": "tsconfig-json"
        },
        {
          "level": 3,
          "title": "基础",
          "slug": "基础"
        },
        {
          "level": 3,
          "title": "编译选项",
          "slug": "编译选项"
        },
        {
          "level": 3,
          "title": "TypeScript 编译",
          "slug": "typescript-编译"
        },
        {
          "level": 2,
          "title": "指定文件",
          "slug": "指定文件"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-2ea09a28",
      "path": "/config.html"
    },
    {
      "title": "动态导入表达式",
      "frontmatter": {},
      "regularPath": "/project/dynamicImportExpressions.html",
      "relativePath": "project/dynamicImportExpressions.md",
      "key": "v-42959f49",
      "path": "/project/dynamicImportExpressions.html"
    },
    {
      "title": "模块",
      "frontmatter": {},
      "regularPath": "/project/modules.html",
      "relativePath": "project/modules.md",
      "key": "v-73098e57",
      "path": "/project/modules.html",
      "headers": [
        {
          "level": 2,
          "title": "全局模块",
          "slug": "全局模块"
        },
        {
          "level": 2,
          "title": "文件模块",
          "slug": "文件模块"
        },
        {
          "level": 2,
          "title": "文件模块详情",
          "slug": "文件模块详情"
        },
        {
          "level": 3,
          "title": "澄清：commonjs, amd, es modules, others",
          "slug": "澄清-commonjs-amd-es-modules-others"
        },
        {
          "level": 3,
          "title": "ES 模块语法",
          "slug": "es-模块语法"
        },
        {
          "level": 3,
          "title": "模块路径",
          "slug": "模块路径"
        },
        {
          "level": 3,
          "title": "什么是 place",
          "slug": "什么是-place"
        },
        {
          "level": 3,
          "title": "重写类型的动态查找",
          "slug": "重写类型的动态查找"
        },
        {
          "level": 3,
          "title": "import/require 仅仅是导入类型",
          "slug": "import-require-仅仅是导入类型"
        },
        {
          "level": 2,
          "title": "global.d.ts",
          "slug": "global-d-ts"
        }
      ]
    },
    {
      "title": "命名空间",
      "frontmatter": {},
      "regularPath": "/project/namespaces.html",
      "relativePath": "project/namespaces.md",
      "key": "v-622dba07",
      "path": "/project/namespaces.html"
    },
    {
      "title": "环境声明",
      "frontmatter": {},
      "regularPath": "/typings/ambient.html",
      "relativePath": "typings/ambient.md",
      "key": "v-297476d7",
      "path": "/typings/ambient.html",
      "headers": [
        {
          "level": 2,
          "title": "声明文件",
          "slug": "声明文件"
        },
        {
          "level": 2,
          "title": "变量",
          "slug": "变量"
        }
      ]
    },
    {
      "title": "可调用的",
      "frontmatter": {},
      "regularPath": "/typings/callable.html",
      "relativePath": "typings/callable.md",
      "key": "v-3bdea20d",
      "path": "/typings/callable.html",
      "headers": [
        {
          "level": 2,
          "title": "一个实际的例子",
          "slug": "一个实际的例子"
        },
        {
          "level": 2,
          "title": "箭头函数",
          "slug": "箭头函数"
        },
        {
          "level": 2,
          "title": "可实例化",
          "slug": "可实例化"
        }
      ]
    },
    {
      "title": "枚举",
      "frontmatter": {},
      "regularPath": "/typings/enums.html",
      "relativePath": "typings/enums.md",
      "key": "v-b1c68552",
      "path": "/typings/enums.html",
      "headers": [
        {
          "level": 2,
          "title": "数字类型枚举与数字类型",
          "slug": "数字类型枚举与数字类型"
        },
        {
          "level": 2,
          "title": "数字类型枚举与字符串类型",
          "slug": "数字类型枚举与字符串类型"
        },
        {
          "level": 2,
          "title": "改变与数字枚举关联的数字",
          "slug": "改变与数字枚举关联的数字"
        },
        {
          "level": 2,
          "title": "使用数字类型作为标志",
          "slug": "使用数字类型作为标志"
        },
        {
          "level": 2,
          "title": "字符串枚举",
          "slug": "字符串枚举"
        },
        {
          "level": 2,
          "title": "常量枚举",
          "slug": "常量枚举"
        },
        {
          "level": 3,
          "title": "常量枚举 preserveConstEnums 选项",
          "slug": "常量枚举-preserveconstenums-选项"
        },
        {
          "level": 2,
          "title": "有静态方法的枚举",
          "slug": "有静态方法的枚举"
        },
        {
          "level": 2,
          "title": "开放式枚举",
          "slug": "开放式枚举"
        }
      ]
    },
    {
      "title": "辨析联合类型",
      "frontmatter": {},
      "regularPath": "/typings/discrominatedUnion.html",
      "relativePath": "typings/discrominatedUnion.md",
      "key": "v-685f24fa",
      "path": "/typings/discrominatedUnion.html",
      "headers": [
        {
          "level": 2,
          "title": "详细的检查",
          "slug": "详细的检查"
        },
        {
          "level": 2,
          "title": "Switch",
          "slug": "switch"
        },
        {
          "level": 2,
          "title": "strictNullChecks",
          "slug": "strictnullchecks"
        },
        {
          "level": 2,
          "title": "Redux",
          "slug": "redux"
        }
      ]
    },
    {
      "title": "异常处理",
      "frontmatter": {},
      "regularPath": "/typings/exceptionsHanding.html",
      "relativePath": "typings/exceptionsHanding.md",
      "key": "v-ca22b292",
      "path": "/typings/exceptionsHanding.html",
      "headers": [
        {
          "level": 2,
          "title": "错误子类型",
          "slug": "错误子类型"
        },
        {
          "level": 3,
          "title": "RangeError",
          "slug": "rangeerror"
        },
        {
          "level": 3,
          "title": "ReferenceError",
          "slug": "referenceerror"
        },
        {
          "level": 3,
          "title": "SyntaxError",
          "slug": "syntaxerror"
        },
        {
          "level": 3,
          "title": "TypeError",
          "slug": "typeerror"
        },
        {
          "level": 3,
          "title": "URIError",
          "slug": "urierror"
        },
        {
          "level": 2,
          "title": "使用 Error",
          "slug": "使用-error"
        },
        {
          "level": 2,
          "title": "你并不需要 throw 抛出一个错误",
          "slug": "你并不需要-throw-抛出一个错误"
        },
        {
          "level": 2,
          "title": "优秀的用例",
          "slug": "优秀的用例"
        },
        {
          "level": 3,
          "title": "不清楚从哪里抛出错误",
          "slug": "不清楚从哪里抛出错误"
        },
        {
          "level": 3,
          "title": "优雅的捕获错误",
          "slug": "优雅的捕获错误"
        },
        {
          "level": 3,
          "title": "没有在类型系统中很好的表示",
          "slug": "没有在类型系统中很好的表示"
        }
      ]
    },
    {
      "title": "Freshness",
      "frontmatter": {},
      "regularPath": "/typings/freshness.html",
      "relativePath": "typings/freshness.md",
      "key": "v-cb193a12",
      "path": "/typings/freshness.html",
      "headers": [
        {
          "level": 2,
          "title": "允许额外的属性",
          "slug": "允许额外的属性"
        },
        {
          "level": 2,
          "title": "用例：React State",
          "slug": "用例-react-state"
        }
      ]
    },
    {
      "title": "泛型",
      "frontmatter": {},
      "regularPath": "/typings/generices.html",
      "relativePath": "typings/generices.md",
      "key": "v-076dbaf7",
      "path": "/typings/generices.html",
      "headers": [
        {
          "level": 2,
          "title": "动机和示例",
          "slug": "动机和示例"
        },
        {
          "level": 2,
          "title": "误用的泛型",
          "slug": "误用的泛型"
        },
        {
          "level": 2,
          "title": "设计模式：方便通用",
          "slug": "设计模式-方便通用"
        },
        {
          "level": 3,
          "title": "配合 axios 使用",
          "slug": "配合-axios-使用"
        }
      ]
    },
    {
      "title": "函数",
      "frontmatter": {},
      "regularPath": "/typings/functions.html",
      "relativePath": "typings/functions.md",
      "key": "v-72dc9137",
      "path": "/typings/functions.html",
      "headers": [
        {
          "level": 2,
          "title": "参数注解",
          "slug": "参数注解"
        },
        {
          "level": 3,
          "title": "返回类型注解",
          "slug": "返回类型注解"
        },
        {
          "level": 3,
          "title": "可选参数",
          "slug": "可选参数"
        },
        {
          "level": 3,
          "title": "重载",
          "slug": "重载"
        },
        {
          "level": 3,
          "title": "函数声明",
          "slug": "函数声明"
        }
      ]
    },
    {
      "title": "索引签名",
      "frontmatter": {},
      "regularPath": "/typings/indexSignatures.html",
      "relativePath": "typings/indexSignatures.md",
      "key": "v-7854de12",
      "path": "/typings/indexSignatures.html",
      "headers": [
        {
          "level": 2,
          "title": "TypeScript 索引签名",
          "slug": "typescript-索引签名"
        },
        {
          "level": 2,
          "title": "声明一个索引签名",
          "slug": "声明一个索引签名"
        },
        {
          "level": 2,
          "title": "所有成员都必须符合字符串的索引签名",
          "slug": "所有成员都必须符合字符串的索引签名"
        },
        {
          "level": 2,
          "title": "使用一组有限的字符串字面量",
          "slug": "使用一组有限的字符串字面量"
        },
        {
          "level": 2,
          "title": "同时拥有 string 和 number 类型的索引签名",
          "slug": "同时拥有-string-和-number-类型的索引签名"
        },
        {
          "level": 2,
          "title": "设计模式：索引签名的嵌套",
          "slug": "设计模式-索引签名的嵌套"
        },
        {
          "level": 2,
          "title": "索引签名中排除某些属性",
          "slug": "索引签名中排除某些属性"
        }
      ]
    },
    {
      "title": "接口",
      "frontmatter": {},
      "regularPath": "/typings/interfaces.html",
      "relativePath": "typings/interfaces.md",
      "key": "v-1e0adf89",
      "path": "/typings/interfaces.html",
      "headers": [
        {
          "level": 2,
          "title": "类可以实现接口",
          "slug": "类可以实现接口"
        },
        {
          "level": 2,
          "title": "注意",
          "slug": "注意"
        },
        {
          "level": 3,
          "title": "并非每个接口都是很容易实现的",
          "slug": "并非每个接口都是很容易实现的"
        }
      ]
    },
    {
      "title": "lib.d.ts",
      "frontmatter": {},
      "regularPath": "/typings/lib.html",
      "relativePath": "typings/lib.md",
      "key": "v-20d9ddf7",
      "path": "/typings/lib.html",
      "headers": [
        {
          "level": 2,
          "title": "使用例子",
          "slug": "使用例子"
        },
        {
          "level": 2,
          "title": "观察 lib.d.ts 的内容",
          "slug": "观察-lib-d-ts-的内容"
        },
        {
          "level": 2,
          "title": "修改原始类型",
          "slug": "修改原始类型"
        },
        {
          "level": 3,
          "title": "Window",
          "slug": "window"
        },
        {
          "level": 3,
          "title": "Math",
          "slug": "math"
        },
        {
          "level": 3,
          "title": "Date",
          "slug": "date"
        },
        {
          "level": 3,
          "title": "string",
          "slug": "string"
        },
        {
          "level": 3,
          "title": "终极 string",
          "slug": "终极-string"
        },
        {
          "level": 2,
          "title": "使用你自己定义的 lib.d.ts",
          "slug": "使用你自己定义的-lib-d-ts"
        },
        {
          "level": 2,
          "title": "编译目标对 lib.d.ts 的影响",
          "slug": "编译目标对-lib-d-ts-的影响"
        },
        {
          "level": 2,
          "title": "--lib 选项",
          "slug": "lib-选项"
        },
        {
          "level": 3,
          "title": "命令行",
          "slug": "命令行"
        },
        {
          "level": 3,
          "title": "config.json",
          "slug": "config-json"
        },
        {
          "level": 2,
          "title": "在旧的 JavaScript 引擎时使用 Polyfill",
          "slug": "在旧的-javascript-引擎时使用-polyfill"
        }
      ]
    },
    {
      "title": "字面量类型",
      "frontmatter": {},
      "regularPath": "/typings/literals.html",
      "relativePath": "typings/literals.md",
      "key": "v-d4852596",
      "path": "/typings/literals.html",
      "headers": [
        {
          "level": 2,
          "title": "字符串字面量",
          "slug": "字符串字面量"
        },
        {
          "level": 2,
          "title": "其他字面量类型",
          "slug": "其他字面量类型"
        },
        {
          "level": 2,
          "title": "推断",
          "slug": "推断"
        },
        {
          "level": 2,
          "title": "使用用例",
          "slug": "使用用例"
        },
        {
          "level": 2,
          "title": "辨析联合类型",
          "slug": "辨析联合类型"
        }
      ]
    },
    {
      "title": "从 JavaScript 迁移",
      "frontmatter": {},
      "regularPath": "/typings/migrating.html",
      "relativePath": "typings/migrating.md",
      "key": "v-043429d2",
      "path": "/typings/migrating.html",
      "headers": [
        {
          "level": 2,
          "title": "减少错误",
          "slug": "减少错误"
        },
        {
          "level": 2,
          "title": "第三方代码",
          "slug": "第三方代码"
        },
        {
          "level": 2,
          "title": "第三方的 NPM 模块",
          "slug": "第三方的-npm-模块"
        },
        {
          "level": 2,
          "title": "额外的非 JavaScript 资源",
          "slug": "额外的非-javascript-资源"
        }
      ]
    },
    {
      "title": "混合",
      "frontmatter": {},
      "regularPath": "/typings/mixins.html",
      "relativePath": "typings/mixins.md",
      "key": "v-66ae3d99",
      "path": "/typings/mixins.html",
      "headers": [
        {
          "level": 2,
          "title": "创建一个构造函数",
          "slug": "创建一个构造函数"
        },
        {
          "level": 2,
          "title": "扩展一个类并且返回它",
          "slug": "扩展一个类并且返回它"
        }
      ]
    },
    {
      "title": "流动的类型",
      "frontmatter": {},
      "regularPath": "/typings/movingTypes.html",
      "relativePath": "typings/movingTypes.md",
      "key": "v-b4331e92",
      "path": "/typings/movingTypes.html",
      "headers": [
        {
          "level": 2,
          "title": "复制类型和值",
          "slug": "复制类型和值"
        },
        {
          "level": 2,
          "title": "捕获变量的类型",
          "slug": "捕获变量的类型"
        },
        {
          "level": 2,
          "title": "捕获类成员的类型",
          "slug": "捕获类成员的类型"
        },
        {
          "level": 2,
          "title": "捕获字符串类型",
          "slug": "捕获字符串类型"
        },
        {
          "level": 2,
          "title": "捕获键的名称",
          "slug": "捕获键的名称"
        }
      ]
    },
    {
      "title": "Never",
      "frontmatter": {},
      "regularPath": "/typings/neverType.html",
      "relativePath": "typings/neverType.md",
      "key": "v-50981f52",
      "path": "/typings/neverType.html",
      "headers": [
        {
          "level": 2,
          "title": "用例：详细的检查",
          "slug": "用例-详细的检查"
        },
        {
          "level": 2,
          "title": "与 void 的差异",
          "slug": "与-void-的差异"
        }
      ]
    },
    {
      "title": "概览",
      "frontmatter": {},
      "regularPath": "/typings/overview.html",
      "relativePath": "typings/overview.md",
      "key": "v-6d54244b",
      "path": "/typings/overview.html",
      "headers": [
        {
          "level": 2,
          "title": "TypeScript 类型系统",
          "slug": "typescript-类型系统"
        },
        {
          "level": 2,
          "title": "基本注解",
          "slug": "基本注解"
        },
        {
          "level": 2,
          "title": "原始类型",
          "slug": "原始类型"
        },
        {
          "level": 2,
          "title": "数组",
          "slug": "数组"
        },
        {
          "level": 2,
          "title": "接口",
          "slug": "接口"
        },
        {
          "level": 2,
          "title": "内联类型注解",
          "slug": "内联类型注解"
        },
        {
          "level": 2,
          "title": "特殊类型",
          "slug": "特殊类型"
        },
        {
          "level": 3,
          "title": "any",
          "slug": "any"
        },
        {
          "level": 3,
          "title": "null 和 undefined",
          "slug": "null-和-undefined"
        },
        {
          "level": 3,
          "title": "void",
          "slug": "void"
        },
        {
          "level": 2,
          "title": "泛型",
          "slug": "泛型"
        },
        {
          "level": 2,
          "title": "联合类型",
          "slug": "联合类型"
        },
        {
          "level": 2,
          "title": "交叉类型",
          "slug": "交叉类型"
        },
        {
          "level": 2,
          "title": "元组类型",
          "slug": "元组类型"
        },
        {
          "level": 2,
          "title": "类型别名",
          "slug": "类型别名"
        },
        {
          "level": 2,
          "title": "最后",
          "slug": "最后"
        }
      ]
    },
    {
      "title": "readonly",
      "frontmatter": {},
      "regularPath": "/typings/readonly.html",
      "relativePath": "typings/readonly.md",
      "key": "v-a276470e",
      "path": "/typings/readonly.html",
      "headers": [
        {
          "level": 2,
          "title": "Readonly",
          "slug": "readonly-2"
        },
        {
          "level": 2,
          "title": "其他的使用用例",
          "slug": "其他的使用用例"
        },
        {
          "level": 3,
          "title": "ReactJS",
          "slug": "reactjs"
        },
        {
          "level": 3,
          "title": "绝对的不可变",
          "slug": "绝对的不可变"
        },
        {
          "level": 3,
          "title": "自动推断",
          "slug": "自动推断"
        },
        {
          "level": 2,
          "title": "与 const 的不同",
          "slug": "与-const-的不同"
        }
      ]
    },
    {
      "title": "ThisType",
      "frontmatter": {},
      "regularPath": "/typings/thisType.html",
      "relativePath": "typings/thisType.md",
      "key": "v-22bccd8d",
      "path": "/typings/thisType.html"
    },
    {
      "title": "类型断言",
      "frontmatter": {},
      "regularPath": "/typings/typeAssertion.html",
      "relativePath": "typings/typeAssertion.md",
      "key": "v-fda1b0d2",
      "path": "/typings/typeAssertion.html",
      "headers": [
        {
          "level": 2,
          "title": "as foo 与 <foo>",
          "slug": "as-foo-与-foo"
        },
        {
          "level": 2,
          "title": "类型断言与类型转换",
          "slug": "类型断言与类型转换"
        },
        {
          "level": 2,
          "title": "类型断言被认为是有害的",
          "slug": "类型断言被认为是有害的"
        },
        {
          "level": 2,
          "title": "双重断言",
          "slug": "双重断言"
        },
        {
          "level": 3,
          "title": "TypeScript 是怎么确定单个断言是否足够",
          "slug": "typescript-是怎么确定单个断言是否足够"
        }
      ]
    },
    {
      "title": "类型兼容性",
      "frontmatter": {},
      "regularPath": "/typings/typeCompatibility.html",
      "relativePath": "typings/typeCompatibility.md",
      "key": "v-032b0557",
      "path": "/typings/typeCompatibility.html",
      "headers": [
        {
          "level": 2,
          "title": "安全性",
          "slug": "安全性"
        },
        {
          "level": 2,
          "title": "结构化",
          "slug": "结构化"
        },
        {
          "level": 2,
          "title": "变体",
          "slug": "变体"
        },
        {
          "level": 2,
          "title": "函数",
          "slug": "函数"
        },
        {
          "level": 3,
          "title": "返回类型",
          "slug": "返回类型"
        },
        {
          "level": 3,
          "title": "参数数量",
          "slug": "参数数量"
        },
        {
          "level": 3,
          "title": "可选的和 rest 参数",
          "slug": "可选的和-rest-参数"
        },
        {
          "level": 3,
          "title": "函数参数类型",
          "slug": "函数参数类型"
        },
        {
          "level": 2,
          "title": "枚举",
          "slug": "枚举"
        },
        {
          "level": 2,
          "title": "类",
          "slug": "类"
        },
        {
          "level": 2,
          "title": "泛型",
          "slug": "泛型"
        },
        {
          "level": 2,
          "title": "脚注：不变性（Invariance）",
          "slug": "脚注-不变性-invariance"
        }
      ]
    },
    {
      "title": "类型保护",
      "frontmatter": {},
      "regularPath": "/typings/typeGuard.html",
      "relativePath": "typings/typeGuard.md",
      "key": "v-22230992",
      "path": "/typings/typeGuard.html",
      "headers": [
        {
          "level": 2,
          "title": "typeof",
          "slug": "typeof"
        },
        {
          "level": 2,
          "title": "instanceof",
          "slug": "instanceof"
        },
        {
          "level": 2,
          "title": "in",
          "slug": "in"
        },
        {
          "level": 2,
          "title": "字面量类型保护",
          "slug": "字面量类型保护"
        },
        {
          "level": 2,
          "title": "使用定义的类型保护",
          "slug": "使用定义的类型保护"
        }
      ]
    },
    {
      "title": "类型推断",
      "frontmatter": {},
      "regularPath": "/typings/typeInference.html",
      "relativePath": "typings/typeInference.md",
      "key": "v-7492fbb7",
      "path": "/typings/typeInference.html",
      "headers": [
        {
          "level": 2,
          "title": "定义变量",
          "slug": "定义变量"
        },
        {
          "level": 2,
          "title": "函数返回类型",
          "slug": "函数返回类型"
        },
        {
          "level": 2,
          "title": "赋值",
          "slug": "赋值"
        },
        {
          "level": 2,
          "title": "结构化",
          "slug": "结构化"
        },
        {
          "level": 2,
          "title": "解构",
          "slug": "解构"
        },
        {
          "level": 2,
          "title": "类型保护",
          "slug": "类型保护"
        },
        {
          "level": 2,
          "title": "警告",
          "slug": "警告"
        },
        {
          "level": 3,
          "title": "小心使用参数",
          "slug": "小心使用参数"
        },
        {
          "level": 3,
          "title": "小心使用返回值",
          "slug": "小心使用返回值"
        },
        {
          "level": 3,
          "title": "noImplicitAny",
          "slug": "noimplicitany"
        }
      ]
    },
    {
      "title": "@types",
      "frontmatter": {},
      "regularPath": "/typings/types.html",
      "relativePath": "typings/types.md",
      "key": "v-ba480312",
      "path": "/typings/types.html",
      "headers": [
        {
          "level": 2,
          "title": "使用 @types",
          "slug": "使用-types"
        },
        {
          "level": 3,
          "title": "全局 @types",
          "slug": "全局-types"
        },
        {
          "level": 3,
          "title": "模块 @types",
          "slug": "模块-types"
        },
        {
          "level": 2,
          "title": "控制全局",
          "slug": "控制全局"
        }
      ]
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/chentong106140",
    "repoLabel": "查看源码",
    "smoothScroll": true,
    "sidebarDepth": 3,
    "navbar": true,
    "logo": "/logos.jpg",
    "nav": [
      {
        "text": "外部链接",
        "target": "_blank",
        "rel": "我是外部链接",
        "link": "http://www.baidu.com"
      },
      {
        "text": "外部链接",
        "target": "_blank",
        "link": "https://jkchao.github.io/typescript-book-chinese/"
      },
      {
        "text": "内部链接",
        "target": "_self",
        "link": ""
      },
      {
        "text": "语言",
        "ariaLabel": "语言菜单",
        "items": [
          {
            "text": "中文",
            "link": "/language/chinese/"
          },
          {
            "text": "英文",
            "link": "/language/japanese/"
          }
        ]
      },
      {
        "text": "历史版本",
        "items": [
          {
            "text": "v1",
            "items": [
              {
                "text": "v1.1.1",
                "link": "/language/v1.1.1/"
              },
              {
                "text": "v1.1.2",
                "link": "/language/v1.1.2/"
              }
            ]
          },
          {
            "text": "v2",
            "items": [
              {
                "text": "v2.1.1",
                "link": "/language/v2.1.1/"
              },
              {
                "text": "v2.1.2",
                "link": "/language/v2.1.2/"
              }
            ]
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "写在前面",
        "path": "/",
        "collapsable": false,
        "children": [
          "/"
        ]
      },
      {
        "title": "TypeScript 项目",
        "collapsable": false,
        "children": [
          "/project/compilationContext",
          "/project/declarationspaces",
          "/project/modules",
          "/project/namespaces",
          "/project/dynamicImportExpressions"
        ]
      },
      {
        "title": "TypeScript 类型系统",
        "collapsable": false,
        "children": [
          "/typings/overview",
          "/typings/migrating",
          "/typings/types",
          "/typings/ambient",
          "/typings/interfaces",
          "/typings/enums",
          "/typings/lib",
          "/typings/functions",
          "/typings/callable",
          "/typings/typeAssertion",
          "/typings/freshness",
          "/typings/typeGuard",
          "/typings/literals",
          "/typings/readonly",
          "/typings/generices",
          "/typings/typeInference",
          "/typings/typeCompatibility",
          "/typings/neverType",
          "/typings/discrominatedUnion",
          "/typings/indexSignatures",
          "/typings/movingTypes",
          "/typings/exceptionsHanding",
          "/typings/mixins",
          "/typings/thisType"
        ]
      }
    ],
    "searchMaxSuggestions": 10,
    "lastUpdated": "上次更新"
  }
}